var data = [
    // offensive
    [
        {
            index: 1,
            name: "Summoner's Wrath",
            ranks: 1,
            desc: "Improves the following Summoner Spells:\n\n|Exhaust:| Reduces target's Magic Resist and Armor by 10\n|Ignite:| Increases Ability Power and Attack Damage by 5 while on cooldown\n|Ghost:| Increases Movement Speed bonus to 35%\n|Garrison:| Allied Garrisoned turrets deal 50% splash damage.",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Fury",
            ranks: 4,
            desc: "+#% Attack Speed",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 3,
            name: "Sorcery",
            ranks: 4,
            desc: "+#% Cooldown Reduction",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 4,
            name: "Butcher",
            ranks: 2,
            desc: "Basic attacks deal # bonus damage to minions and monsters",
            rankInfo: [2, 4],
        },
        {
            index: 5,
            name: "Touchy",
            ranks: 2,
            desc: "Increase damage dealt by #% against targets who damaged you in the last 3 seconds",
            rankInfo: [1, 2],
        },
        {
            index: 6,
            name: "Deadliness",
            ranks: 4,
            perlevel: 1,
            desc: "+# Attack Damage per level\n(# Attack Damage at champion level 18)",
            rankInfo: [0.166, 0.333, 0.498, 0.664],
        },
        {
            index: 7,
            name: "Blast",
            ranks: 4,
            perlevel: 1,
            desc: "+# Ability Power per level\n(# Ability Power at champion level 18)",
            rankInfo: [0.25, 0.5, 0.75, 1],
        },
        {
            index: 8,
            name: "Irritating",
            ranks: 3,
            desc: "Your first ability or basic attack against a champion deals additional true damage equal to #% of the target's current health over 3 seconds. (10 second cooldown)",
            rankInfo: [1, 2, 3],
        },
        {
            index: 9,
            name: "Justice",
            ranks: 1,
            desc: "Increase damage dealt by 2%",
            rankInfo: [],
            parent: 4,
        },
        {
            index: 10,
            name: "Weapon Expertise",
            ranks: 1,
            desc: "+8% Armor Penetraton",
            rankInfo: [],
            parent: 5,
        },
        {
            index: 11,
            name: "Arcane Knowledge",
            ranks: 1,
            desc: "+8% Magic Penetration",
            rankInfo: [],
            parent: 6,
        },
        {
            index: 12,
            name: "Annoying",
            ranks: 1,
            desc: "Your first ability or basic attack against a champion reduces his armor and magic resist by 2% for 3 seconds (10 second cooldown)",
            rankInfo: [],
			parent: 7,
        },
        {
            index: 13,
            name: "Lethality",
            ranks: 2,
            desc: "+#% Critical Strike Damage\n (#% for melee champions)",
            rankInfo: [2.5, 5],
            rankInfo2: [5, 10],
        },
        {
            index: 14,
            name: "Brute Force",
            ranks: 2,
            desc: "+# Attack Damage",
            rankInfo: [1.5, 3],
        },
        {
            index: 15,
            name: "Mental Force",
            ranks: 3,
            desc: "# Ability Power",
            rankInfo: [2, 4, 6],
        },
        {
            index: 16,
            name: "Spellsword",
            ranks: 1,
            desc: "Deals 5% of your Ability Power in magic damage to the target on each basic attack",
            rankInfo: [],
        },
        {
            index: 17,
            name: "Frenzy",
            ranks: 1,
            desc: "Grants 10% attack speed for 2 seconds after landing a critical hit",
            rankInfo: [],
            parent: 12,
        },
        {
            index: 18,
            name: "Sunder",
            ranks: 3,
            desc: "+# Armor Penetration",
            rankInfo: [2, 4, 6],
        },
        {
            index: 19,
            name: "Archmage",
            ranks: 4,
            desc: "Increases Ability Power by #%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 20,
            name: "Inspire",
            ranks: 2,
            desc: "Aura that grants +# Attack Damage and +# Ability Power to you and your allies (800 range)",
            rankInfo: [1, 2],
            rankInfo2: [2, 4],
        },
        {
            index: 22,
            name: "Destroy",
            ranks: 1,
            desc: "Increases damage dealt by 5% against targets who's movement is impaired",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Enfeeble",
            ranks: 1,
            desc: "Your abilities and basic attacks against targets below 30% health slow them by 20% (10% for ranged basic attacks)",
            rankInfo: [],
        },
    ],
        // defensive
    [
        {
            index: 1,
            name: "Summoner's Resolve",
            ranks: 1,
            desc: "Improves the following Summoner Spells:\n\n|Cleanse:| Increases duration of disable reduction by 1 second\n|Heal:| Passively increases Health by 5 per level\n|Smite:| Grants 10 bonus gold on use\n|Barrier:| Increases Barrier shield amount by 20",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Durability",
            ranks: 4,
            perlevel: 1,
            desc: "+# Health per level\n(+# Health at champion level 18)",
            rankInfo: [1.5, 3, 4.5, 6],
        },
        {
            index: 3,
            name: "Unyielding",
            ranks: 2,
            desc: "Reduces the damage taken from enemy champions by #",
            rankInfo: [1, 2],
        },
        {
            index: 4,
            name: "Relentless",
            ranks: 3,
            desc: "Reduces the effectiveness of slows by #%",
            rankInfo: [5, 10, 15],
        },
        {
            index: 5,
            name: "Hunter",
            ranks: 2,
            desc: "Each time a monster hits you, you receives a mark hunter that lasts 3 seconds (stacks up to # marks). Each mark grants 0.5 damage reduction against monsters.",
            rankInfo: [4, 8],
        },
        {
            index: 6,
            name: "Veteran's Scars",
            ranks: 1,
            desc: "+25 Health",
            rankInfo: [],
			parent: 1,
        },
        {
            index: 7,
            name: "Block",
            ranks: 1,
            desc: "Reduces damage taken from champion basic attacks by 3",
            rankInfo: [],
			parent: 2,
        },
        {
            index:8,
            name: "Tenacious",
            ranks: 4,
            desc: "Reduces the duration of crowd control effects by #% (stacks multiplicatively with Tenacity)",
            rankInfo: [4, 8, 12, 16],
			parent: 3,
        },
        {
            index: 9,
            name: "Bladed Armor",
            ranks: 1,
            desc: "Each mark of hunter deals 1 true damage to any enemy monster that attacks you",
            rankInfo: [],
			parent: 4,
        },
        {
            index: 10,
            name: "Juggernaut",
            ranks: 3,
            desc: "Increases your maximum Health by #%",
            rankInfo: [1.5, 2.75, 4],
        },
        {
            index: 11,
            name: "Hardiness",
            ranks: 4,
            desc: "+# Armor",
            rankInfo: [1.5, 3, 4.5, 6],
        },
        {
            index: 12,
            name: "Resistance",
            ranks: 3,
            desc: "+# Magic Resist",
            rankInfo: [2, 4, 6],
        },
        {
            index: 13,
            name: "Safeguard",
            ranks: 1,
            desc: "Reduces damage taken from turrets by 5% +1% per nearby allied champion",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Recovery",
            ranks: 1,
            desc: "Restores 0.5% of your missing health every 5 seconds",
            rankInfo: [],
			parent: 9,
        },
        {
            index: 15,
            name: "Dominant",
            ranks: 1,
            desc: "Increases your bonus armor by 6% against enemies who's health is below 50%",
            rankInfo: [],
			parent: 10,
        },
        {
            index: 16,
            name: "Survive",
            ranks: 1,
            desc: "You gain 1 magic resist per level when your movement is impaired (18 magic resist at champion level 18)",
            rankInfo: [],
			parent: 11,
        },
        {
            index: 17,
            name: "Defender",
            ranks: 1,
            desc: "Grants +1 Armor and Magic Resist for each nearby enemy champion",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Legendary Armor",
            ranks: 3,
            desc: "Increases bonus Armor and Magic Resist by +#%",
            rankInfo: [2, 4, 6],
        },
        {
            index: 19,
            name: "Reinforced Armor",
            ranks: 1,
            desc: "Reduce damage taken from critical strikes by 10%",
            rankInfo: [],
        },
        {
            index: 20,
            name: "Protection",
            ranks: 2,
            desc: "Aura that grants +# Armor and Magic Resist to you and your allies (800 range)",
            rankInfo: [1, 2],
        },
        {
            index: 22,
            name: "Honor Guard",
            ranks: 1,
            desc: "Reduces damage taken from all sources by 3%",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Confident",
            ranks: 1,
            desc: "Increases your armor by 1 per 20 Attack damage and your magic resist by 1 per 30 Ability Power",
            rankInfo: [],
        },
    ],
    [
        {
            index: 1,
            name: "Summoner's Insight",
            ranks: 1,
            desc: "Improves the following Summoner Spells:\n\n|Teleport:| Reduces cast time by # second\n|Revive:| Grants bonus Health on Revive for 2 minutes\n|Flash:| Reduces cooldown by 15 seconds\n|Clarity:| Increases Mana restored by 25%\n|Clairvoyance:| Grants additional vision of enemy units revealed",
            rankInfo: [0.5],
        },
        {
            index: 2,
            name: "Wanderer",
            ranks: 3,
            desc: "Grants +#% increased Movement Speed when out of combat",
            rankInfo: [0.66, 1.33, 2],
        },
        {
            index: 3,
            name: "Greed",
            ranks: 4,
            desc: "Grants an additional +# gold every 10 seconds",
            rankInfo: [0.5, 1, 1.5, 2],
        },
        {
            index: 4,
            name: "Meditation",
            ranks: 3,
            desc: "+# Mana Regen per 5 seconds",
            rankInfo: [1, 2, 3],
        },
        {
            index: 5,
            name: "Biscuiteer",
            ranks: 1,
            desc: "Start the game with a regenerative biscuit that restores 80 Health and 50 Mana over 10 seconds",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Coward",
            ranks: 1,
            desc: "Increases your Movement Speed by 1% for each nearby enemy champion",
            rankInfo: [],
            parent: 1,
        },
        {
            index: 7,
            name: "Wealth",
            ranks: 2,
            desc: "Increases starting gold by #",
            rankInfo: [25, 50],
            parent: 2,
        },
        {
            index: 8,
            name: "Serenity",
            ranks: 1,
            desc: "+6 Mana Regen per 5 seconds when out of combat",
            rankInfo: [],
            parent: 3,
        },
        {
            index: 9,
            name: "Explorer",
            ranks: 1,
            desc: "On Summoners Rift, grants a Ward at the start of the game that can be placed to reveal the surrounding area for 60 seconds. On all other maps, grants 25 starting gold.",
            rankInfo: [],
            parent: 4,
        },
        {
            index: 10,
            name: "Runic Affinity",
            ranks: 1,
            desc: "Increases the duration of shrine, relic, quest, and neutral monster buffs by 20%",
            rankInfo: [],
        },
        {
            index: 11,
            name: "Grasping",
            ranks: 2,
            desc: "Killing anything grants +# gold",
            rankInfo: [1, 2],
            parent: 6,
        },
        {
            index: 12,
            name: "Vampirism",
            ranks: 3,
            desc: "+#% Lifesteal and Spell Vamp",
            rankInfo: [1, 2, 3],
        },
        {
            index: 13,
            name: "Pickpocket",
            ranks: 1,
            desc: "Grants 5 gold for melee champions and 3 gold for ranged champions each time you perform a basic attack against an enemy champion (5 second cooldown)",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Mastermind",
            ranks: 3,
            desc: "Reduces the cooldown of Summoner Spells by #%",
            rankInfo: [4, 7, 10],
        },
        {
            index: 15,
            name: "Awareness",
            ranks: 4,
            desc: "Increases Experience earned by #%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 16,
            name: "Cruelness",
            ranks: 1,
            desc: "Killing anything restores 1% of your missing health (3% for champions)",
            rankInfo: [],
            parent: 11,
        },
        {
            index: 17,
            name: "Repairer",
            ranks: 2,
            desc: "When your Wards expire, you gain +# gold for a Sight Ward and +# gold for a Vision Ward",
            rankInfo:  [4, 6],
            rankInfo2: [6, 15],
        },
        {
            index: 18,
            name: "Artifacer",
            ranks: 2,
            desc: "Reduces the cooldown of activated items by #%",
            rankInfo: [7.5, 15],
        },
        {
            index: 19,
            name: "Wisdom of the Wild",
            ranks: 1,
            desc: "Increases experience gained from monsters by 3%",
            rankInfo: [],
            parent: 14,
        },
        {
            index: 20,
            name: "Charge",
            ranks: 1,
            desc: "Aura that grants +# Movement Speed to you and your allies (800 range)",
            rankInfo: [2, 4],
        },
        {
            index: 22,
            name: "Nimble",
            ranks: 1,
            desc: "Grants 3% increased Movement Speed",
            rankInfo: [],
        },
        {
            index: 23,
            name: "Reach",
            ranks: 1,
            desc: "Your abilities and basic attack's range is increased by 5%",
            rankInfo: [],
        },
    ]
];
